---
- hosts: app
  become: true
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'docker', 'docker-compose']
    - git:
        repo: https://github.com/ColinRoye/item_service.git
        dest: /app
        force: yes
    - name: Run mix commands
      shell: cd /app
               && echo y | sudo docker system prune
               && sudo sysctl -w vm.max_map_count=524288
               && npm install
               && sudo nohup docker-compose up&
      ignore_errors: yes
      become: True
